USE master
GO


IF DB_ID('StaffinfoAuthDB') IS NOT NULL
  EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N'StaffinfoAuthDB'
GO

USE master
GO

IF DB_ID('StaffinfoAuthDB') IS NOT NULL
  DROP DATABASE StaffinfoAuthDB
GO

IF DB_ID('StaffinfoAuthDB') IS NULL
  CREATE DATABASE StaffinfoAuthDB
  ON PRIMARY (
  NAME = N'StaffinfoAuthDB',
  FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\StaffinfoAuthDB.mdf',
  SIZE = 4160 KB,
  MAXSIZE = UNLIMITED,
  FILEGROWTH = 1024 KB
  )
  LOG ON (
  NAME = N'StaffinfoAuthDB_log',
  FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\StaffinfoAuthDB_log.ldf',
  SIZE = 1040 KB,
  MAXSIZE = UNLIMITED,
  FILEGROWTH = 10 %
  )
GO

ALTER DATABASE StaffinfoAuthDB
SET
ANSI_NULL_DEFAULT OFF,
ANSI_NULLS OFF,
ANSI_PADDING OFF,
ANSI_WARNINGS OFF,
ARITHABORT OFF,
AUTO_CLOSE ON,
AUTO_CREATE_STATISTICS ON,
AUTO_SHRINK OFF,
AUTO_UPDATE_STATISTICS ON,
AUTO_UPDATE_STATISTICS_ASYNC OFF,
COMPATIBILITY_LEVEL = 110,
CONCAT_NULL_YIELDS_NULL OFF,
CURSOR_CLOSE_ON_COMMIT OFF,
CURSOR_DEFAULT GLOBAL,
DATE_CORRELATION_OPTIMIZATION OFF,
DB_CHAINING OFF,
HONOR_BROKER_PRIORITY OFF,
MULTI_USER,
NESTED_TRIGGERS = ON,
NUMERIC_ROUNDABORT OFF,
PAGE_VERIFY CHECKSUM,
PARAMETERIZATION SIMPLE,
QUOTED_IDENTIFIER OFF,
READ_COMMITTED_SNAPSHOT ON,
RECOVERY SIMPLE,
RECURSIVE_TRIGGERS OFF,
TRANSFORM_NOISE_WORDS = OFF,
TRUSTWORTHY OFF
WITH ROLLBACK IMMEDIATE
GO

ALTER DATABASE StaffinfoAuthDB
COLLATE Cyrillic_General_CI_AS
GO

ALTER DATABASE StaffinfoAuthDB
SET ENABLE_BROKER
GO

ALTER DATABASE StaffinfoAuthDB
SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE StaffinfoAuthDB
SET FILESTREAM (NON_TRANSACTED_ACCESS = OFF)
GO

IF DB_ID('StaffinfoAuthDB') IS NOT NULL
  ALTER AUTHORIZATION ON DATABASE::StaffinfoAuthDB TO [IBAGOMEL\DSHAUCHUK]
GO